language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script:
- touch foo
deploy:
  provider: pypi
  user: martin.majlis
  password:
    secure: ePuAH8c1HBzDMGiZIW/zHy0zmp6wvYBy5CT0+y9dEFyWxLtYSv0tOXEOL/zDxGborz+iL7Zlqlgafxtgeyd7PaBUPpWcMRP9mpWi2WoX3Prww57JGhRfGi7oWeqj1EM4sAdEmQo4Ww0CMdJOON/K1lp05mArNazZx4UPcQyeq2XqK+6RemPC/IMvxi0/lIpYADC7CElLSA3pvqSUv57IvuJC+Tu7M1H8QrgjfdmAMQ45s3Q1XUivaeCSicQx2x9xmoa+Gt3KI1+gP8kDhIlDECbY3C1F2L8G1K0gGuT27rNHjFdIHpEhj6fE4PdPLBFS/0FYVtGGFqiZpN9dY9CAtk8yXoeI0H3gCAuvMm7wcGqctETWUB2A2sy0/2YJo5VMQKnpft6KS/I9KbJxjV3RSLPpKIbreTypv2a1JI/0XT/KeYunyF2e8UxgYvo/zvL8Qka1UYBF7hqRmMc29jpVRAIB9TsZ1lgJ89jshEll06wHICtfF7UvoDXMOBv8zQSXTeARG3iqOetXLYnDlmfXTfWHbKldXII90P14gWw2O/JBXBKIs3VpXB117MARQyTY+kLgOV+I/9ZeGfrFCx3pc2+aLbh0UiFLK974w1cO3/Vhl+7jFVW1TWrA9rmLAZS0B3JUzlcDIBN9RFugeoW45h2VqZk1jiW4120dGFPmAzU=
  on:
    tags: true
    branch: master

after_sucess:
- CODECLIMATE_REPO_TOKEN=f71b8777af3523a62c1b487e7d590e1894353daa codeclimate-test-reporter
