language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script:
- touch foo
deploy:
  provider: pypi
  user: martin.majlis
  password:
    secure: CmCUyxswP4ZOonOaFt+6gdWvZwW7Ia2gcipoLSNPfaVfxVTgFSen471uj4NuO8k0i4gUZHZBY06GIgEodE3JSlZ2pju6+FkiCaMdrWJmMCkzQfeXn/jKuz+gOSIgmJ84e+yXZ1sgbiJsLuCImPNarAGrLyFO9LBm1VXUW6ZOUL+xdFbF87MHJBcptSLmWQfeLNOVFrzuZgYNLmzpxd2+bpJBJhdYme7KThq82TnxTsDCnzlLL6r3cmunym1AZqRxGodaVp1v0j8eMlHdzJH1mB4w0sWucRRTMH10a0qPR3AdwGxNiYswR64sn1VuDpooxyYng4jrwcOYNRfR0k2XhC7Vpn4NaV1A11Pwg7kkyIQimHkWoM63mIA+u/4OVzFfsrjmErZ9HsaXVkJjqJPSzhtygtqKFIdOWUnSeNGByJjjNvg7xemrTLRLVv3PQ2pg8wiuU/H8RuPcfrDfKxwt854LktLd2HuNh3ljlM3l/5/jWkB4aqYNUl38AJ43NuUHDYrtJdrq3lKpXYAMy6c4uFKGm4pz2sIEZUCVMUqIrltWoSkxGiK7GVW+MdZ1M+ZWJBYvZsb9b9sI9dX1CVuSWgPE/GzHXU6Rrv/1AyqBRHypcHEGGtpkHBHPdMpDrAUbb+51TlQn4C7b+kRCq6s6n/e3Zoq2ilb9eNFwZhleong=
  on:
    tags: true
    branch: master

after_sucess:
- CODECLIMATE_REPO_TOKEN=f71b8777af3523a62c1b487e7d590e1894353daa codeclimate-test-reporter
