language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script:
- date
deploy:
  provider: pypi
  skip_existing: true
  user: martin.majlis
  password:
    secure: GwW600dya+08B+vTpvMMzAannK880HSV/lSqedn3DjxOUSJTRAK0GzhG9IOYDfY4mR/1UYmklfYocjvOH/SBKEo3kfV5k6mhNYp0g2/Jem2ZOq5XyNKNCH3xuz4c7UlSA6CgRu0nzaZvACdsXA3jLJPFXBJkAJvZ4hQL5mwxurc+OeyPNTMRfgT6qB0YrZFtCW8E+rcM2Yn4HwWImDw7OaHm324wEXKTJGmeEn/x4/ZJropm8eTvNsupigp78bJGw3DdhlC2T+JM8ZtPpNOOfoP9K5OA0j5ckSWDHdQ1DVCh7kySPetrvGuWvwKQt4peAU4/03COcQzQJLf0v1I6kflTGSzRYGT9GskD/srt89znUj1MeYmR4W+nM+MqK+KUXvd2HgO8YozpngiEjfgox8VkOh7lJ/zuZNf0uBPxBWiaoYQkxN1gZ2PbqySYebpIDiVoiSiZtyxkEREEXyEoEnCcoZ9CKh90CiOXEdCCqPVFMq+Xky/AofdqCgYgJUXASB01aqUxfM6tPslBNVHn4KJSmKLrYjX9OcZhCcRKDyC+hVFnLFqsBA7ng8gjUA7itQZDmchBXqCc6PzsD3KFKGjqHFoafRGjX3pNSlTDvQojwZk6WPiJrq0llFAGs84sqJOlA7j5ofeF1XZwGLSl2SMznqFFDm57Wx+sg5p9iXs=
  on:
    tags: true

after_sucess:
- CODECLIMATE_REPO_TOKEN=f71b8777af3523a62c1b487e7d590e1894353daa codeclimate-test-reporter
