language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script:
- touch foo
deploy:
  provider: pypi
  user: martin.majlis
  password:
    secure: cfOZnkHDF+cJtHJofOlvaQXT35ucdTfzQs6ZVN6+1EqZJ0pIo1WX80jW36iSmzv2wOOaJi0hLqjQRCScMXRD6EK1FwO7I2wDeAwRNpG2HLrhr7ZwfMuGEYzdP+FqwnigincUzbTn7xAGYbD4u7om0JFCWmDLXM/3IHyfyIFxkh74OmedFtM+bCSvdGgOwWGf/CKhrQ3MpcT3dKc9yLaonqXVkNDzf2y4en/YL4PoLirBxMJYFxkNV55haFG23Qxd/dKunTMLpXya6y8epJ3p6M2sxaIBm2Ey+44xS/1ZEpevLhbyWHMDcwtcZCw5rcz60Lt2GGhqronBaTjvwKPeD5qhkd+QzRPICdjcbl/YdkZsDaJX6rcYxfqEgZbCxhjBNvMkseMSESxzEU1qy73R+LuxU6OFJx/LMdqzkC+6QJHifIFv+6UKYZq7gn1rnKVas7b7KHDODRtaduJP77wU3/24ieDNKp4Fd/p1V8l54+6qMte7YBjSG+hS7Y8qI7BCG4LZYeupZLqBIdX6HL9+/ol4sPhy9+rzPPOJhLhpKY7SlROpM66qz0xffvb/lg8480QDF/ZjUS7Z+8TMEtAG3CgtF1gABhS/KCdQBv3Pmb8uxbW1u0PCp28eY5JqdhetiPYg6wJDdgnc8jKm+fwgtlphLyvHTwgJGcrUc2qC5vY=
  on:
    tags: true
    branch: master
